ls:
    .dir: snake_case
    .py: snake_case

ignore:
    - .git
    - .github
    - __MACOSX
    - "**/__MACOSX"
    - .DS_Store
    - "**/.DS_Store"
    - .github
    - .pytest_cache
    - "**/.pytest_cache"
    - .ruff_cache
    - "**/.ruff_cache"
    - .venv
    - "**/.venv"
    - __pycache__
    - "**/__pycache__"
    - "**/*.egg-info"
    - "**/*.log"
